### ISSUE TITLE
npm run comunica-sparql -- arguments

### ISSUE THREAD

**Issue by simonvbrae** [comunica/Tutorial-Comunica-Web-Service#2]
Remember that when using `npm run comunica sparql` instead of `comunica-sparql`, you must place "--" between comunica-sparql and the arguments for this command, otherwise options might be interpreted as node options instead of comunica-sparql options.

Example:
´npm run comunica-sparql -h` shows npm help info
`npm run comunica-sparql -- -h` shows comunica-sparql help info

**Comment by joachimvh** [comment]
Added a note for this, thanks
